sequenceDiagram
    participant C as Coding Night
    participant P as Público
    C->>P: Transmissão de conteúdo 
    Note right of C: Com "pequenos" atrasos 
    P-->>C: Likes, compartilhamento!
    P->>C: Dúvidas
    Note right of P: Só leremos perguntas não-ofensivas
    C-->P: Resposta às perguntas